//// Skill proposal types — the unit of agent-led skill evolution.
////
//// A `SkillProposal` captures a candidate new (or updated) skill that the
//// Remembrancer derived from a CBR pattern. Proposals flow through the
//// Promotion Safety Gate (deterministic pre-filter + D' scorer + rate
//// limit) and either become Active skills or are dropped, with the outcome
//// recorded in the per-day skills log.
////
//// This module is types-only — no I/O. The pattern detector
//// (`src/skills/pattern.gleam`) emits these; the proposal log
//// (`src/skills/proposal_log.gleam`) persists them; the gate (PR-D) acts
//// on them.

// Copyright (C) 2026 Seamus Brady <seamus@corvideon.ie>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

import gleam/dynamic/decode
import gleam/float
import gleam/json
import gleam/list
import gleam/option.{type Option, None, Some}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// A candidate skill, before the safety gate makes a decision.
pub type SkillProposal {
  SkillProposal(
    /// Slug-style identifier the proposed skill would receive.
    proposal_id: String,
    /// Human-readable name.
    name: String,
    /// Short description for the system prompt.
    description: String,
    /// Markdown body — the actual instruction the agent would receive.
    body: String,
    /// Agent scope this proposal targets.
    agents: List(String),
    /// Domain tags for context activation (may be empty for unscoped).
    contexts: List(String),
    /// CBR case IDs that constitute the supporting evidence.
    source_cases: List(String),
    /// Aggregate confidence from the supporting cases (0.0-1.0).
    confidence: Float,
    /// Which agent generated the proposal — typically "remembrancer".
    proposed_by: String,
    /// ISO 8601 timestamp.
    proposed_at: String,
    /// Result of the conflict-detection step. Filled in by the conflict
    /// classifier (LLM-driven in PR-D); STUB returns Complementary in
    /// PR-C so the proposal still flows.
    conflict: ConflictClassification,
  )
}

/// How the new proposal relates to existing Active skills scoped to the
/// same agents.
pub type ConflictClassification {
  /// Independent of every existing skill — accepted as a new entry.
  Complementary
  /// Says roughly the same as `target_id` — auto-merge as a supersession
  /// of that skill.
  Redundant(target_id: String)
  /// Replaces `target_id` with a refined version. The old skill moves to
  /// Archived; the new one takes its slot.
  Supersedes(target_id: String)
  /// Conflicts with `target_id` — the gate rejects. The agent must propose
  /// a new version of `target_id` (Supersedes) instead.
  Contradictory(target_id: String)
  /// The classifier hasn't run yet (PR-C STUB). Treated as Complementary
  /// at the gate until PR-D wires the LLM classifier.
  Unknown
}

/// Lifecycle events recorded in the per-day skills log. Each variant is
/// an immutable event — supersession is expressed by writing a new event,
/// never by editing earlier ones.
pub type SkillLogEntry {
  /// A new proposal was generated by the Remembrancer.
  SkillProposed(timestamp: String, proposal: SkillProposal)
  /// The gate accepted a proposal and the skill became Active. Records
  /// the proposal_id, the path of the SKILL.md that was written, and the
  /// agent scope of the new skill. The agent scope is captured so the
  /// gate's same-scope cooldown check can find recent promotions
  /// targeting the same agents.
  SkillCreated(
    timestamp: String,
    proposal_id: String,
    skill_id: String,
    skill_path: String,
    agents: List(String),
  )
  /// The gate rejected a proposal. Records the reason.
  SkillRejected(timestamp: String, proposal_id: String, reason: String)
  /// An Active skill was archived. The supersedes_id field is set when
  /// the archival happened because a newer version was promoted.
  SkillArchived(
    timestamp: String,
    skill_id: String,
    reason: String,
    supersedes_id: Option(String),
  )
}

// ---------------------------------------------------------------------------
// JSON encoders/decoders
// ---------------------------------------------------------------------------

pub fn encode_proposal(p: SkillProposal) -> json.Json {
  json.object([
    #("proposal_id", json.string(p.proposal_id)),
    #("name", json.string(p.name)),
    #("description", json.string(p.description)),
    #("body", json.string(p.body)),
    #("agents", json.array(p.agents, json.string)),
    #("contexts", json.array(p.contexts, json.string)),
    #("source_cases", json.array(p.source_cases, json.string)),
    #("confidence", json.float(p.confidence)),
    #("proposed_by", json.string(p.proposed_by)),
    #("proposed_at", json.string(p.proposed_at)),
    #("conflict", encode_conflict(p.conflict)),
  ])
}

pub fn encode_conflict(c: ConflictClassification) -> json.Json {
  case c {
    Complementary -> json.object([#("kind", json.string("complementary"))])
    Redundant(target_id:) ->
      json.object([
        #("kind", json.string("redundant")),
        #("target_id", json.string(target_id)),
      ])
    Supersedes(target_id:) ->
      json.object([
        #("kind", json.string("supersedes")),
        #("target_id", json.string(target_id)),
      ])
    Contradictory(target_id:) ->
      json.object([
        #("kind", json.string("contradictory")),
        #("target_id", json.string(target_id)),
      ])
    Unknown -> json.object([#("kind", json.string("unknown"))])
  }
}

pub fn encode_log_entry(entry: SkillLogEntry) -> json.Json {
  case entry {
    SkillProposed(timestamp:, proposal:) ->
      json.object([
        #("event", json.string("proposed")),
        #("timestamp", json.string(timestamp)),
        #("proposal", encode_proposal(proposal)),
      ])
    SkillCreated(timestamp:, proposal_id:, skill_id:, skill_path:, agents:) ->
      json.object([
        #("event", json.string("created")),
        #("timestamp", json.string(timestamp)),
        #("proposal_id", json.string(proposal_id)),
        #("skill_id", json.string(skill_id)),
        #("skill_path", json.string(skill_path)),
        #("agents", json.array(agents, json.string)),
      ])
    SkillRejected(timestamp:, proposal_id:, reason:) ->
      json.object([
        #("event", json.string("rejected")),
        #("timestamp", json.string(timestamp)),
        #("proposal_id", json.string(proposal_id)),
        #("reason", json.string(reason)),
      ])
    SkillArchived(timestamp:, skill_id:, reason:, supersedes_id:) -> {
      let base = [
        #("event", json.string("archived")),
        #("timestamp", json.string(timestamp)),
        #("skill_id", json.string(skill_id)),
        #("reason", json.string(reason)),
      ]
      let with_supersedes = case supersedes_id {
        Some(id) -> list.append(base, [#("supersedes_id", json.string(id))])
        None -> base
      }
      json.object(with_supersedes)
    }
  }
}

// Decoders
pub fn proposal_decoder() -> decode.Decoder(SkillProposal) {
  use proposal_id <- decode.field("proposal_id", decode.string)
  use name <- decode.field("name", decode.string)
  use description <- decode.field("description", decode.string)
  use body <- decode.field("body", decode.string)
  use agents <- decode.field("agents", decode.list(decode.string))
  use contexts <- decode.field("contexts", decode.list(decode.string))
  use source_cases <- decode.field("source_cases", decode.list(decode.string))
  use confidence <- decode.field("confidence", number_decoder())
  use proposed_by <- decode.field("proposed_by", decode.string)
  use proposed_at <- decode.field("proposed_at", decode.string)
  use conflict <- decode.optional_field("conflict", Unknown, conflict_decoder())
  decode.success(SkillProposal(
    proposal_id:,
    name:,
    description:,
    body:,
    agents:,
    contexts:,
    source_cases:,
    confidence:,
    proposed_by:,
    proposed_at:,
    conflict:,
  ))
}

fn conflict_decoder() -> decode.Decoder(ConflictClassification) {
  use kind <- decode.field("kind", decode.string)
  case kind {
    "complementary" -> decode.success(Complementary)
    "redundant" -> {
      use target_id <- decode.field("target_id", decode.string)
      decode.success(Redundant(target_id:))
    }
    "supersedes" -> {
      use target_id <- decode.field("target_id", decode.string)
      decode.success(Supersedes(target_id:))
    }
    "contradictory" -> {
      use target_id <- decode.field("target_id", decode.string)
      decode.success(Contradictory(target_id:))
    }
    _ -> decode.success(Unknown)
  }
}

fn number_decoder() -> decode.Decoder(Float) {
  decode.one_of(decode.float, [
    decode.int |> decode.map(fn(n) { float.add(0.0, int_to_float(n)) }),
  ])
}

@external(erlang, "erlang", "float")
fn int_to_float(n: Int) -> Float
