#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Springdrift — shared setup functions
# Sourced by setup-linux.sh, setup-macos.sh, and tests
# ─────────────────────────────────────────────────────────────────────────────

REQUIRED_GLEAM_MAJOR=1
REQUIRED_GLEAM_MINOR=11

# ── Colours (can be overridden before sourcing) ─────────────────────────────
GREEN="${GREEN:-\033[0;32m}"
YELLOW="${YELLOW:-\033[1;33m}"
RED="${RED:-\033[0;31m}"
BOLD="${BOLD:-\033[1m}"
NC="${NC:-\033[0m}"

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}!${NC} $1"; }
fail() { echo -e "  ${RED}✗${NC} $1"; exit 1; }

# ── Preflight ────────────────────────────────────────────────────────────────

check_repo_root() {
  if [[ ! -f "${1:-.}/gleam.toml" ]]; then
    return 1
  fi
  return 0
}

check_not_root() {
  [[ "$(id -u)" -ne 0 ]]
}

check_springdrift_writable() {
  local dir="${1:-.springdrift}"
  if [[ -d "$dir" ]]; then
    [[ -w "$dir" ]]
  else
    return 0
  fi
}

# ── Gleam version ────────────────────────────────────────────────────────────

parse_gleam_version() {
  echo "$1" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
}

gleam_version_ok() {
  local ver="$1"
  if [[ -z "$ver" ]]; then
    return 1
  fi
  local major minor
  major=$(echo "$ver" | cut -d. -f1)
  minor=$(echo "$ver" | cut -d. -f2)
  if [[ "$major" -gt "$REQUIRED_GLEAM_MAJOR" ]] || \
     { [[ "$major" -eq "$REQUIRED_GLEAM_MAJOR" ]] && [[ "$minor" -ge "$REQUIRED_GLEAM_MINOR" ]]; }; then
    return 0
  fi
  return 1
}

# ── Config generation ────────────────────────────────────────────────────────

generate_config() {
  local output_file="$1"
  local provider="${2:-anthropic}"
  local agent_name="${3:-Springdrift}"
  local sandbox_available="${4:-false}"
  local ollama_available="${5:-false}"
  local comms_enabled="${6:-false}"
  local comms_address="${7:-}"
  local comms_recipients_toml="${8:-[]}"
  local backup_remote="${9:-}"
  local script_name="${10:-setup.sh}"

  cat > "$output_file" << TOML
# ─────────────────────────────────────────────────────────────────────────────
# Springdrift config — generated by $script_name
# ─────────────────────────────────────────────────────────────────────────────

provider = "$provider"
max_tokens = 4096
max_turns = 8
max_consecutive_errors = 3
gui = "web"
log_verbose = false
dprime_config = ".springdrift/dprime.json"

[agent]
name = "$agent_name"
version = "Springdrift Mk-3"

[anthropic]
task_model = "claude-haiku-4-5-20251001"
reasoning_model = "claude-opus-4-6"

[narrative]
threading = true
summaries = false

[dprime]
normative_calculus_enabled = true

[sandbox]
enabled = $sandbox_available

[cbr]
# embedding_enabled = $ollama_available

[comms]
enabled = $comms_enabled
$(if [[ "$comms_enabled" == "true" ]]; then
  echo "from_address = \"$comms_address\""
  echo "allowed_recipients = $comms_recipients_toml"
  echo "from_name = \"$agent_name\""
fi)

[web]
# port = 12001

[scheduler]
# max_autonomous_cycles_per_hour = 20

[backup]
enabled = true
mode = "periodic"
# interval_ms = 300000
$(if [[ -n "$backup_remote" ]]; then echo "remote_url = \"$backup_remote\""; fi)

[forecaster]
# enabled = false
TOML
}

# ── Env file generation ──────────────────────────────────────────────────────

generate_env_file() {
  local output_file="$1"
  local anthropic_key="${2:-}"
  local mistral_key="${3:-}"
  local vertex_project="${4:-}"
  local brave_key="${5:-}"
  local jina_key="${6:-}"
  local agentmail_key="${7:-}"
  local web_token="${8:-}"
  local script_name="${9:-setup.sh}"

  {
    echo "# Springdrift environment — generated by $script_name"
    echo "# Source this file before running: source $output_file && gleam run"
    echo ""
    [[ -n "$anthropic_key" ]] && echo "export ANTHROPIC_API_KEY=\"$anthropic_key\"" || true
    [[ -n "$mistral_key" ]] && echo "export MISTRAL_API_KEY=\"$mistral_key\"" || true
    [[ -n "$vertex_project" ]] && echo "export VERTEX_PROJECT_ID=\"$vertex_project\"" || true
    [[ -n "$brave_key" ]] && echo "export BRAVE_API_KEY=\"$brave_key\"" || true
    [[ -n "$jina_key" ]] && echo "export JINA_API_KEY=\"$jina_key\"" || true
    [[ -n "$agentmail_key" ]] && echo "export AGENTMAIL_API_KEY=\"$agentmail_key\"" || true
    [[ -n "$web_token" ]] && echo "export SPRINGDRIFT_WEB_TOKEN=\"$web_token\"" || true
  } > "$output_file"
}

generate_systemd_env_file() {
  local output_file="$1"
  local anthropic_key="${2:-}"
  local mistral_key="${3:-}"
  local vertex_project="${4:-}"
  local brave_key="${5:-}"
  local jina_key="${6:-}"
  local agentmail_key="${7:-}"
  local web_token="${8:-}"

  {
    echo "# Springdrift environment — generated by setup-linux.sh"
    [[ -n "$anthropic_key" ]] && echo "ANTHROPIC_API_KEY=$anthropic_key" || true
    [[ -n "$mistral_key" ]] && echo "MISTRAL_API_KEY=$mistral_key" || true
    [[ -n "$vertex_project" ]] && echo "VERTEX_PROJECT_ID=$vertex_project" || true
    [[ -n "$brave_key" ]] && echo "BRAVE_API_KEY=$brave_key" || true
    [[ -n "$jina_key" ]] && echo "JINA_API_KEY=$jina_key" || true
    [[ -n "$agentmail_key" ]] && echo "AGENTMAIL_API_KEY=$agentmail_key" || true
    [[ -n "$web_token" ]] && echo "SPRINGDRIFT_WEB_TOKEN=$web_token" || true
  } > "$output_file"
}

verify_env_file() {
  local env_file="$1"
  local provider="$2"

  if [[ ! -f "$env_file" ]]; then
    return 1
  fi

  (
    source "$env_file"
    case "$provider" in
      anthropic)
        [[ -n "${ANTHROPIC_API_KEY:-}" ]]
        ;;
      mistral)
        [[ -n "${MISTRAL_API_KEY:-}" ]]
        ;;
      vertex)
        [[ -n "${VERTEX_PROJECT_ID:-}" ]]
        ;;
      local|mock)
        return 0
        ;;
      *)
        return 1
        ;;
    esac
  )
}

# ── Port check ───────────────────────────────────────────────────────────────

check_port_available() {
  local port="$1"

  if command -v lsof &>/dev/null; then
    if lsof -i ":${port}" -sTCP:LISTEN &>/dev/null; then
      return 1
    fi
    return 0
  elif command -v ss &>/dev/null; then
    if ss -tlnp 2>/dev/null | grep -q ":${port} "; then
      return 1
    fi
    return 0
  else
    return 0
  fi
}

# ── TOML recipients formatting ──────────────────────────────────────────────

format_recipients_toml() {
  local recipients="$1"
  if [[ -z "$recipients" ]]; then
    echo "[]"
  else
    echo "[$(echo "$recipients" | sed 's/[[:space:]]*,[[:space:]]*/", "/g; s/^/"/; s/$/"/' )]"
  fi
}
