#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Test 3: Config generation (#32, #34)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$SCRIPT_DIR/harness.sh"
source "$REPO_ROOT/scripts/lib/setup-common.sh"

TMPDIR_BASE=$(mktemp -d)
trap 'rm -rf "$TMPDIR_BASE"' EXIT

echo -e "${BOLD}Config generation${NC}"

# ── Basic config ─────────────────────────────────────────────────────────────

cfg="$TMPDIR_BASE/basic.toml"
generate_config "$cfg" "anthropic" "TestAgent" "false" "false" "false" "" "[]" "" "test.sh"
CONTENT=$(cat "$cfg")

it "generates a file"
assert_file_exists "$cfg"

it "sets provider to anthropic"
assert_contains "$CONTENT" 'provider = "anthropic"'

it "sets agent name"
assert_contains "$CONTENT" 'name = "TestAgent"'

it "sets sandbox disabled"
assert_contains "$CONTENT" 'enabled = false'

it "uses port 12001 (not 8080)"
assert_contains "$CONTENT" '# port = 12001'
assert_not_contains "$CONTENT" '8080'

it "includes script name in header"
assert_contains "$CONTENT" 'generated by test.sh'

it "has max_tokens"
assert_contains "$CONTENT" 'max_tokens = 4096'

it "has max_turns"
assert_contains "$CONTENT" 'max_turns = 8'

it "has dprime_config path"
assert_contains "$CONTENT" 'dprime_config = ".springdrift/dprime.json"'

# ── Different provider ───────────────────────────────────────────────────────

cfg2="$TMPDIR_BASE/mistral.toml"
generate_config "$cfg2" "mistral" "MistralBot" "true" "true" "false" "" "[]" "" "test.sh"
CONTENT2=$(cat "$cfg2")

it "sets provider to mistral"
assert_contains "$CONTENT2" 'provider = "mistral"'

it "sets sandbox enabled when available"
assert_contains "$CONTENT2" 'enabled = true'

# ── Comms enabled ────────────────────────────────────────────────────────────

cfg3="$TMPDIR_BASE/comms.toml"
generate_config "$cfg3" "anthropic" "CommsBot" "false" "false" "true" \
  "bot@agentmail.to" '["alice@example.com", "bob@example.com"]' "" "test.sh"
CONTENT3=$(cat "$cfg3")

it "enables comms"
assert_contains "$CONTENT3" 'enabled = true'

it "sets from_address"
assert_contains "$CONTENT3" 'from_address = "bot@agentmail.to"'

it "sets allowed_recipients"
assert_contains "$CONTENT3" 'allowed_recipients'

it "sets from_name from agent name"
assert_contains "$CONTENT3" 'from_name = "CommsBot"'

# ── Comms disabled ───────────────────────────────────────────────────────────

it "does not include from_address when comms disabled"
assert_not_contains "$CONTENT" 'from_address'

# ── Backup remote ────────────────────────────────────────────────────────────

cfg4="$TMPDIR_BASE/backup.toml"
generate_config "$cfg4" "anthropic" "Agent" "false" "false" "false" "" "[]" \
  "git@github.com:user/data.git" "test.sh"
CONTENT4=$(cat "$cfg4")

it "includes backup remote when provided"
assert_contains "$CONTENT4" 'remote_url = "git@github.com:user/data.git"'

it "does not include backup remote when empty"
assert_not_contains "$CONTENT" 'remote_url'

# ── Recipients formatting ────────────────────────────────────────────────────

it "formats empty recipients as []"
assert_eq "$(format_recipients_toml "")" "[]"

it "formats single recipient"
result=$(format_recipients_toml "alice@example.com")
assert_contains "$result" 'alice@example.com'

it "formats multiple recipients"
result=$(format_recipients_toml "alice@example.com, bob@example.com")
assert_contains "$result" 'alice@example.com'

report
